version: '3'

services:
  
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s docker-entrypoint.sh bash -c "npm install && node index.js"
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init_mysql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

  nginx:
    build: 
      context: nginx
    container_name: nginx
    ports: 
      - "8080:80"
    depends_on:
      - app